### ISSUE TITLE
条件式が冗長

### ISSUE THREAD

**Issue by c011933347** [c0a2106423/ProjExD#15]
https://github.com/c0a2106423/ProjExD/blob/b51b37c1b85d2284f9e3258c09c0f69a1897768c/Ex04/dodge_bomb.py#L44-L51

条件式が冗長で可読性に悪影響を及ぼす可能性があります。
条件式中の変数の値がTrueにしかならない場合は、「== True」の部分を削除しましょう。

**Comment by c0a2106423** [comment]
上のコミットで修正しました。
