### ISSUE TITLE
Bombコンストラクタでの座標がNoneになるときの挙動

### ISSUE THREAD

**Issue by c011933347** [c0a2106423/ProjExD#16]
https://github.com/c0a2106423/ProjExD/blob/b51b37c1b85d2284f9e3258c09c0f69a1897768c/Ex04/dodge_bomb.py#L88-L89

bomb_xがNoneになる場合は考慮されていますが、bomb_yがNoneの場合は考慮されていません。
仕様変更に弱く、誤解を生む危険性があると思います。

**Comment by c0a2106423** [comment]
上記のコミットで修正しました。コメントで想定した場合を明記しました。
